/**
 * AI Music Production Studio - PLAYBACK & CONSOLE ENGINE (player.js)[cite: 1]
 * Purpose: Complete Spotify-styled horizontal player controller layer.[cite: 1]
 * Manages states: play, pause, stops, timelines, tracks, and local lyrics systems.[cite: 1]
 */

// Core Tracking Pointer Memory Arrays
let dynamicTrackPointer = -1;
let localTrackArray = [];
let lyricsUpdaterInterval = null;
let simulatedTrackDuration = 180; // Standard 3-minute fallback limit variable
let currentElapsedTime = 0;
let trackStateIsPlaying = false;

document.addEventListener("DOMContentLoaded", () => {
    initializeAudioPlayerConsole();
});

/**
 * Prepares the audio player shell, timeline scrubbers, and event hooks[cite: 1].
 */
function initializeAudioPlayerConsole() {
    buildStructuralPlayerControls();
    registerGlobalCrossModuleListeners();
    registerInternalUIInteractions();
}

/**
 * Builds standard transport control buttons dynamically into the footer layout structure[cite: 1].
 */
function buildStructuralPlayerControls() {
    const consoleContainer = document.getElementById("sticky-audio-player");
    if (!consoleContainer) return;

    // Clean structural template injection mapping your Spotify specifications[cite: 1]
    consoleContainer.innerHTML = `
        <!-- Left Deck: Track Metadata Frame Details -->
        <div class="player-track-wrapper">
            <img id="playerImage" src="logo/logo.png" onerror="this.src='logo.png'" alt="Art Media Layout">
            <div class="music-info">
                <h4 id="playerTitle">Select Studio Track</h4>
                <p id="player-subtitle">Ready to Stream</p>
            </div>
        </div>

        <!-- Center Deck: Transport Operations Engine Matrix -->
        <div class="player-center-deck">
            <!-- Hidden Iframe Channel Core -->
            <div class="video-player" style="display:none; position:absolute; width:1px; height:1px;">
                <iframe id="youtubePlayer" src="" allow="autoplay" frameborder="0"></iframe>
            </div>

            <!-- Interactive Transport Device Core Row[cite: 1] -->
            <div class="player-transport-controls">
                <button id="p-prev-btn" class="transport-btn" title="Previous Track"><i class="fa-solid fa-backward-step"></i></button>
                <button id="p-toggle-btn" class="transport-btn master-toggle" title="Play / Pause"><i class="fa-solid fa-play"></i></button>
                <button id="p-stop-btn" class="transport-btn" title="Stop System Playback"><i class="fa-solid fa-stop"></i></button>
                <button id="p-next-btn" class="transport-btn" title="Next Track"><i class="fa-solid fa-forward-step"></i></button>
            </div>

            <!-- Timeline/Progress Slider Infrastructure[cite: 1] -->
            <div class="timeline-scrubber-block">
                <span id="p-current-time" class="playback-time">00:00</span>
                <div id="p-scrub-container" class="progress-slider-container">
                    <div class="player-progress-bar">
                        <div id="p-progress-fill" class="progress-fill-node" style="width: 0%"></div>
                    </div>
                </div>
                <span id="p-duration-time" class="playback-time">03:00</span>
            </div>
        </div>

        <!-- Right Deck: Mixing Terminals & Metadata Feeds -->
        <div class="player-right-deck">
            <button id="player-lyrics-btn" title="Sync Live Lyrics"><i class="fa-solid fa-microphone"></i></button>
            <a id="player-external-link" href="#" target="_blank" class="text-[10px] bg-zinc-950 border border-zinc-800 px-2.5 py-1.5 rounded text-zinc-400 hover:text-white flex items-center gap-1 font-bold">
                YOUTUBE <i class="fa-solid fa-arrow-up-right-from-square text-[8px]"></i>
            </a>
            
            <!-- Master Volume Controls Cluster[cite: 1] -->
            <div class="volume-control-cluster">
                <button id="p-volume-toggle" class="volume-icon-btn"><i class="fa-solid fa-volume-high"></i></button>
                <div id="p-volume-track" class="volume-slider-track">
                    <div class="volume-progress-bar">
                        <div id="p-volume-fill" class="volume-fill-node" style="width: 80%"></div>
                    </div>
                </div>
            </div>
        </div>`;
}

/**
 * Hooks into cross-script communications generated by app.js triggers.
 */
function registerGlobalCrossModuleListeners() {
    window.addEventListener("StudioModulePlayRequest", event => {
        const incomingTrack = event.detail;
        
        // Sync regional playlists if loaded from parent app context data loops
        if (window.studioTrackCache && window.studioTrackCache.length > 0) {
            localTrackArray = window.studioTrackCache;
            dynamicTrackPointer = localTrackArray.findIndex(t => t.youtubeId === incomingTrack.id);
        }

        executeTrackPlaybackLifecycle(incomingTrack.id, incomingTrack.title, incomingTrack.meta, incomingTrack.lyrics);
    });
}

/**
 * Registers click events for the media player controls[cite: 1].
 */
function registerInternalUIInteractions() {
    const toggleBtn = document.getElementById("p-toggle-btn");
    const stopBtn = document.getElementById("p-stop-btn");
    const nextBtn = document.getElementById("p-next-btn");
    const prevBtn = document.getElementById("p-prev-btn");
    const scrubber = document.getElementById("p-scrub-container");
    const volumeTrack = document.getElementById("p-volume-track");

    if (toggleBtn) toggleBtn.addEventListener("click", togglePlaybackState);
    if (stopBtn) stopBtn.addEventListener("click", stopPlaybackLifecycle);
    if (nextBtn) nextBtn.addEventListener("click", triggerNextTrack);
    if (prevBtn) prevBtn.addEventListener("click", triggerPreviousTrack);
    
    // Process seek timeline parameter shifts
    if (scrubber) {
        scrubber.addEventListener("click", event => {
            const rect = scrubber.getBoundingClientRect();
            const ratio = (event.clientX - rect.left) / rect.width;
            currentElapsedTime = Math.floor(ratio * simulatedTrackDuration);
            updateVisualTimelineMetrics();
        });
    }

    // Process fluid volume configuration feedback
    if (volumeTrack) {
        volumeTrack.addEventListener("click", event => {
            const rect = volumeTrack.getBoundingClientRect();
            const percentage = Math.max(0, Math.min(100, Math.round(((event.clientX - rect.left) / rect.width) * 100)));
            document.getElementById("p-volume-fill").style.width = `${percentage}%`;
            
            const icon = document.querySelector("#p-volume-toggle i");
            if (icon) {
                if (percentage === 0) icon.className = "fa-solid fa-volume-xmark";
                else if (percentage < 50) icon.className = "fa-solid fa-volume-low";
                else icon.className = "fa-solid fa-volume-high";
            }
        });
    }
}

/**
 * Coordinates tracking configurations and starts the playback engine.
 */
function executeTrackPlaybackLifecycle(id, title, meta, lyricsFile) {
    const consoleContainer = document.getElementById("sticky-audio-player");
    if (!consoleContainer) return;

    consoleContainer.classList.remove("hidden");

    // Cache parameters into the shared DOM context window
    window.currentLoadedTrackId = id;
    window.currentLoadedTrackTitle = title;
    window.currentLyricsFilePath = lyricsFile || `lyrics/${id}.txt`;

    // Map track layout values
    document.getElementById("playerTitle").innerText = title;
    document.getElementById("player-subtitle").innerText = meta;
    document.getElementById("playerImage").src = `https://img.youtube.com/vi/${id}/hqdefault.jpg`;
    document.getElementById("player-external-link").href = `https://www.youtube.com/watch?v=${id}`;
    
    // Inject streaming nodes into target source layers
    document.getElementById("youtubePlayer").src = `https://www.youtube.com/embed/${id}?autoplay=1&enablejsapi=1`;

    // Reset tracking state timers
    trackStateIsPlaying = true;
    currentElapsedTime = 0;
    simulatedTrackDuration = 210; // Sets a clean standard runtime loop value
    
    updateTransportToggleUI(true);
    initializeScrubberEngineLoop();
}

function togglePlaybackState() {
    if (!window.currentLoadedTrackId) return;
    trackStateIsPlaying = !trackStateIsPlaying;
    updateTransportToggleUI(trackStateIsPlaying);
    
    const iframe = document.getElementById("youtubePlayer");
    if (iframe && iframe.contentWindow) {
        const command = trackStateIsPlaying ? '{"event":"command","func":"playVideo","args":""}' : '{"event":"command","func":"pauseVideo","args":""}';
        iframe.contentWindow.postMessage(command, '*');
    }
}

function stopPlaybackLifecycle() {
    stopScrubberEngineLoop();
    currentElapsedTime = 0;
    trackStateIsPlaying = false;
    updateVisualTimelineMetrics();
    updateTransportToggleUI(false);

    const iframe = document.getElementById("youtubePlayer");
    if (iframe) iframe.src = ""; // Clears network data down to default paths
}

function triggerNextTrack() {
    if (localTrackArray.length === 0 || dynamicTrackPointer === -1) return;
    dynamicTrackPointer = (dynamicTrackPointer + 1) % localTrackArray.length;
    loadCachedPointerTrack();
}

function triggerPreviousTrack() {
    if (localTrackArray.length === 0 || dynamicTrackPointer === -1) return;
    dynamicTrackPointer = (dynamicTrackPointer - 1 + localTrackArray.length) % localTrackArray.length;
    loadCachedPointerTrack();
}

function loadCachedPointerTrack() {
    const target = localTrackArray[dynamicTrackPointer];
    if (target) {
        executeTrackPlaybackLifecycle(target.youtubeId, target.title, `${target.language} • ${target.category}`, target.lyricsFile || "");
    }
}

/**
 * Manages interval loops for updating the seek timeline slider[cite: 1].
 */
function initializeScrubberEngineLoop() {
    stopScrubberEngineLoop();
    lyricsUpdaterInterval = setInterval(() => {
        if (trackStateIsPlaying) {
            currentElapsedTime++;
            if (currentElapsedTime >= simulatedTrackDuration) {
                triggerNextTrack(); // Auto-advance track when timer hits runtime boundary thresholds
            } else {
                updateVisualTimelineMetrics();
            }
        }
    }, 1000);
}

function stopScrubberEngineLoop() {
    if (lyricsUpdaterInterval) clearInterval(lyricsUpdaterInterval);
}

function updateVisualTimelineMetrics() {
    const elapsedMinutes = Math.floor(currentElapsedTime / 60).toString().padStart(2, '0');
    const elapsedSeconds = (currentElapsedTime % 60).toString().padStart(2, '0');
    document.getElementById("p-current-time").innerText = `${elapsedMinutes}:${elapsedSeconds}`;

    const totalMinutes = Math.floor(simulatedTrackDuration / 60).toString().padStart(2, '0');
    const totalSeconds = (simulatedTrackDuration % 60).toString().padStart(2, '0');
    document.getElementById("p-duration-time").innerText = `${totalMinutes}:${totalSeconds}`;

    const percentage = (currentElapsedTime / simulatedTrackDuration) * 100;
    document.getElementById("p-progress-fill").style.width = `${percentage}%`;
}

function updateTransportToggleUI(isPlaying) {
    const icon = document.querySelector("#p-toggle-btn i");
    if (icon) {
        icon.className = isPlaying ? "fa-solid fa-pause" : "fa-solid fa-play";
    }
}
